name: learningapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
  firebase_admob: ^0.9.3


dev_dependencies:
  flutter_launcher_icons: "^0.6.1"

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - data.json
    - assets/images/splash.png

flutter_icons:
  image_path: "assets/launcher/finalicon.png"
  image_path_ios: "assets/launcher/finalicon.png"
  android: true
  ios: true



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # see https://flutter.dev/custom-fonts/#from-packages
